name: test-deploy

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make application ymls
        run: |
          cd ./gg-pingpong-api/src/main/resources
          echo "${{ secrets.MIGRATE_APPLICATION_YML }}" | base64 -d > application.yml
        shell: bash

      - name: Test with Gradle
        run: ./gradlew clean test

      - name: Build with Gradle
        run: ./gradlew clean build -x test
